# Tab widgets package
from scripts.client.tabs.portfolio_history_tab import PortfolioHistoryTab
from scripts.client.tabs.text_dialog import TextDialog
from scripts.client.tabs.add_ticker_dialog import AddTickerDialog
from scripts.client.tabs.status_poller import StatusPoller
from scripts.client.tabs.forecasts_tab import ForecastsTab
from scripts.client.tabs.consensus_tab import ConsensusTab
from scripts.client.tabs.tickers_tab import TickersTab
from scripts.client.tabs.providers_tab import ProvidersTab
from scripts.client.tabs.keys_sub_tab import _KeysSubTab
from scripts.client.tabs.bybit_settings_sub_tab import _BybitSettingsSubTab
from scripts.client.tabs.new_method_dialog import NewMethodDialog
from scripts.client.tabs.prompts_tab import PromptsTab
from scripts.client.tabs.system_log_tab import SystemLogTab
from scripts.client.tabs.numeric_table_widget_item import NumericTableWidgetItem
from scripts.client.tabs.price_data_tab import PriceDataTab
from scripts.client.tabs.indicators_tab import IndicatorsTab
from scripts.client.tabs.accounts_tab import AccountsTab
from scripts.client.tabs.scheduler_tab import SchedulerTab
from scripts.client.tabs.orders_tab import OrdersTab
from scripts.client.tabs.trades_tab import TradesTab
from scripts.client.tabs.trading_tab import TradingTab
from scripts.client.tabs.forecast_runs_tab import ForecastRunsTab
from scripts.client.tabs.settings_tab import SettingsTab
